env:
  browser: true
  es2021: true
extends:
  - eslint:recommende
  - plugin:vue/essential
  - plugin:@typescript-eslint/recommended
  - "@nuxtjs/eslint-config-typescript"
  - prettier
parserOptions:
  ecmaVersion: latest
  parser: '@typescript-eslint/parser'
  sourceType: module
plugins:
  - vue
  - '@typescript-eslint'
rules:
  linebreak-style:
    - error
    - unix
